name: Build ChoreoLib Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The full version string, i.e. 2024.0.0-alpha-1 or 2024.1.1 with no leading "v"
        required: true

jobs:
  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/roborio-cross-ubuntu:2024-22.04
            artifact-name: ChoreoLib-Athena
            build-options: "-Ponlylinuxathena"
          - container: wpilib/ubuntu-base:22.04
            artifact-name: ChoreoLib-Linux
            build-options: "-Ponlylinuxx86-64"
          - container: wpilib/raspbian-cross-ubuntu:bullseye-22.04
            artifact-name: ChoreoLib-Arm32
            build-options: "-Ponlylinuxarm32"
          - container: wpilib/aarch64-cross-ubuntu:bullseye-22.04
            artifact-name: ChoreoLib-Arm64
            build-options: "-Ponlylinuxarm64"
    name: "[ChoreoLib] Build - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-22.04
    container: ${{ matrix.container }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./choreolib

      - name: Set version
        run: sed -i "s/0.0.0/${{ github.event.inputs.version }}/g" publish.gradle
        working-directory: ./choreolib

      - name: Ensure spotless is applied
        run: ./gradlew spotlessApply
        working-directory: ./choreolib

      - name: Build
        run: ./gradlew build -PreleaseMode ${{ matrix.build-options }}
        working-directory: ./choreolib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: choreolib/build/allOutputs

  build-host:
    env:
      MACOSX_DEPLOYMENT_TARGET: 12
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            artifact-name: ChoreoLib-Win64
          - os: macos-13
            artifact-name: ChoreoLib-macOS
    name: "[ChoreoLib] Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Set version (Windows)
        if: matrix.os == 'windows-2022'
        run: sed -i "s/0.0.0/${{ github.event.inputs.version }}/g" publish.gradle
        working-directory: ./choreolib
      - name: Set version (Mac)
        if: matrix.os == 'macos-13'
        run: sed -i '' "s/0.0.0/${{ github.event.inputs.version }}/g" publish.gradle
        working-directory: ./choreolib

      - name: Ensure spotless is applied
        run: ./gradlew spotlessApply
        working-directory: ./choreolib

      - name: Build
        run: ./gradlew build -Pbuildalldesktop -PreleaseMode
        working-directory: ./choreolib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: choreolib/build/allOutputs

  combine:
    name: "[ChoreoLib] Combine"
    needs: [build-docker, build-host]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout build-tools
        uses: actions/checkout@v4
        with:
          repository: wpilibsuite/build-tools

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: combiner/products/build/allOutputs

      - name: Flatten Artifacts
        run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Combine
        run: ./gradlew publish -Pthirdparty
        working-directory: combiner

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChoreoLib-Maven-v${{ github.event.inputs.version }}
          path: ~/releases
